### PR TITLE
An attempt to add paging support in a generic way.

### PR DESCRIPTION
**Pull request by mivano**

### CODE REVIEW

**Comment by Daniel-Spindler-Mandalay** [comment]
I did some testing on this branch and it works for calls I make that need more pages and no known impact to calls for single pages.
Looks good to go.

**Comment by DanielSpindler83** [comment]
I did some testing on this branch and it works for calls I make that need more pages and no known impact to calls for single pages.
Looks good to go.

**Comment by mivano** [comment]
Thanks for validating. By the way, I did not want to overrule your PR, as you also took the time to come up with an implementation. So I hope you are okay with this approach as well?

**Comment by DanielSpindler83** [comment]
100% ok with this approach. It is nice and clean. I am enjoying the learning and engagement. Thanks for checking.

**Comment by MvRoo** [comment]
I have been testing costByResource, which didn't support paging before, and it is looking fine until now. Have exported > 38k lines on one occasion.

**Comment by mivano** [comment]
Thanks for validating this change guys! I will merge it and prepare a package.

**Pull request merged**
